lsi: false
safe: true
source: [https://github.com/darecoder-git/darecoder-git]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
